version: "3.8"

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "80:80"        # HTTP traffic
      - "8081:8080"    # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/traefik.yml:/etc/traefik/traefik.yml"

  fastapi:
    build:
      context: ./app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`localhost`)"
      - "traefik.http.routers.fastapi.entrypoints=web"
    expose:
      - "8000"
