entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

api:
  dashboard: true
  insecure: true

providers:
  docker:
    exposedByDefault: false

tls:
  certificates:
    - certFile: "/certs/server.crt"
      keyFile: "/certs/server.key"
